export const USER_LOGGED_IN= 'USER_LOGGED_IN';
export const LOCATION_CHANGED = 'LOCATION_CHANGED';
export const SUBSCRIBED_USER = 'SUBSCRIBED_USER';
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';